name: Build and test

on: [push]

env:
  XCODE_WORKSPACE: "AeroGearPush.xcworkspace"
  XCODE_SCHEME: "AeroGearPush"
  XCODE_SCHEME_TEST: "AeroGearPushTests"
  SIMULATOR: "iPhone 8"
  OS: "13.3"

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1

    - name: Installing deps
      run: pod install

    - name: Compile
      run: xcodebuild
        CODE_SIGNING_REQUIRED=NO
        CODE_SIGN_IDENTITY=
        PROVISIONING_PROFILE=
        -sdk iphonesimulator
        -destination "platform=iOS Simulator,name=${SIMULATOR},OS=${OS}"
        -workspace $XCODE_WORKSPACE
        -scheme $XCODE_SCHEME
        clean build

    - name: test
      run: xcodebuild
        CODE_SIGNING_REQUIRED=NO
        CODE_SIGN_IDENTITY=
        PROVISIONING_PROFILE=
        -sdk iphonesimulator
        -destination "platform=iOS Simulator,name=${SIMULATOR},OS=${OS}"
        -workspace $XCODE_WORKSPACE
        -scheme $XCODE_SCHEME_TEST
        test  
